import createClient from "openapi-fetch";
import type { paths } from "./schema.js";

/**
 * Typed API client. Types come from `schema.d.ts`, generated by
 * `pnpm openapi:generate` (which reads /openapi.json from the running API).
 *
 * The baseUrl is empty because Vite proxies /api to the API in dev; in prod
 * you would set it to the deployed API origin.
 */
export const api = createClient<paths>({ baseUrl: "/api/v1" });
